### ISSUE TITLE
应当添加对时功能

### ISSUE THREAD

**Issue by kengwang** [kengwang/EarthQuakeWarning#1]
应当支持 NTP 时间对时, 以防止时间差距过大导致倒计时出问题

**Comment by Initial-heart-1** [comment]
建议考虑直接调 WindowsTime 对齐 ntp.ntsc.ac.cn，每间隔 30min 执行一次，或参考 [Microsoft Learn](https://learn.microsoft.com/zh-cn/windows-server/networking/windows-time-service/configuring-systems-for-high-accuracy) 调整系统配置。当然，最优的解决方案是软件自己获得网络时间。

**Comment by Initial-heart-1** [comment]
请注意，上述链接中给出的配置不适用于移动设备，且它提供的精度远超地震预警需求，如果你准备使用，建议修改以降低能耗。

**Comment by kengwang** [comment]
若要进行对时操作, 需要进行权限提升, 我感觉可能不太需要, 毕竟现在能跑的基本都是 Windows 10 以上的系统, 系统时间不会存在影响报警的问题.

**Comment by Initial-heart-1** [comment]
> 若要进行对时操作, 需要进行权限提升, 我感觉可能不太需要, 毕竟现在能跑的基本都是 Windows 10 以上的系统, 系统时间不会存在影响报警的问题.

事实上现在常见版本的 Windows10 时差普遍＞1s，例如，现在你可以访问 time.is 验证你计算机的时差。相信你明白地震预警时 1s 的意义。按道理我们应该在设计时尽可能减少延时以使用户可以在最短时间内做出反应并避免伤亡。

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/202854358-f831485a-9538-475c-a11f-dc77fef5ab17.png)

😂

**Comment by Initial-heart-1** [comment]
so，如你所见。

**Comment by Initial-heart-1** [comment]
![image](https://user-images.githubusercontent.com/63091661/202854445-c7c903c4-5047-43ed-8160-9374ac6cbbd8.png)
这是在我计算机上测得的结果，你可以在 [这里](https://www.initbili.top/2022/76edc2121eba/) 得到一样的精确度，但如文中所说，没有需求的话不推荐这么做。

**Comment by kengwang** [comment]
我的对时服务 (W32Time) 被设置成了手动, 从 2022 年 9 月 开始就未进行过对时

**Comment by Initial-heart-1** [comment]
> 我的对时服务 (W32Time) 被设置成了手动, 从 2022 年 9 月 开始就未进行过对时

不，并不是被设置，而是它默认就是手动的，但似乎不影响自动对时。如果期望获得高度精确的时间，你必须手动改为自动。

**Comment by kengwang** [comment]
time.windows.com 似乎在中国大陆无法进行访问
![image](https://user-images.githubusercontent.com/30862240/202854577-e5ba52a9-0220-432f-a184-ea22e492aed3.png)

若非进行权限提升, 对时可能仅能通过软件内部维持一个 30 分钟更新一次的时间差进行维护

**Comment by Initial-heart-1** [comment]
> time.windows.com 似乎在中国大陆无法进行访问 ![image](https://user-images.githubusercontent.com/30862240/202854577-e5ba52a9-0220-432f-a184-ea22e492aed3.png)
> 
> 若非进行权限提升, 对时可能仅能通过软件内部维持一个 30 分钟更新一次的时间差进行维护

并不，我在我遇到的任意网络环境下均可访问，但延时极高。事实上，我摸到任何一台 Windows 计算机的时候第一件要做的事就是调整 NTP。

**Comment by Initial-heart-1** [comment]
另外，在软件内部已经足够，系统时间并不是你需要管的，你只需要保证用于预警的时间准确。

**Comment by Initial-heart-1** [comment]
如果期望得到高精度的系统时间，上面发送的文章中有一个脚本，运行就可以马上获得，配置这些总共的用时不会超过半分钟。

**Comment by kengwang** [comment]
> 另外，在软件内部已经足够，系统时间并不是你需要管的，你只需要保证用于预警的时间准确。

感谢交流
由于最近并未准备对此软件进行更新, 可能会在很久之后才会进行提交和更新
请谅解

**Comment by Initial-heart-1** [comment]
> > 另外，在软件内部已经足够，系统时间并不是你需要管的，你只需要保证用于预警的时间准确。
> 
> 感谢交流 由于最近并未准备对此软件进行更新, 可能会在很久之后才会进行提交和更新 请谅解

了解，我们正在做一个地震预警相关的项目，我突然想起来找找 Github 所以找到了你的项目。浏览你的源码后我们惊讶地发现你的思路和我们高度重合。请问你有 API 的详细文档吗？我们虽然早就取得了 API 地址，但一直找不到文档，对部分参数完全无法理解，但在这里浏览部分 issue 后我们得到了一些答案。

**Comment by kengwang** [comment]
Reply: https://github.com/kengwang/EarthQuakeWarning/issues/1#issuecomment-1320894179

如果需要进一步交流, 可以添加 QQ 等即时通讯方式联系, 应该可以在我的 Profile 里找到相关信息

**Comment by Initial-heart-1** [comment]
> Reply: [#1 (comment)](https://github.com/kengwang/EarthQuakeWarning/issues/1#issuecomment-1320894179)
> 
> 如果需要进一步交流, 可以添加 QQ 等即时通讯方式联系, 应该可以在我的 Profile 里找到相关信息

当然。之前草草的浏览你的 Profile 页，并没有注意到 QQ 邮箱的存在。

**Comment by kengwang** [comment]
此问题似乎已经通过假如 NTP 功能解决
