### ISSUE TITLE
非常感谢软件作者

### ISSUE THREAD

**Issue by irasutoya** [kengwang/EarthQuakeWarning#3]
今天的地震我通过电脑收到了预警信息，这个功能非常值得开发！感谢，希望以后越做越好！

**Comment by kengwang** [comment]
感谢反馈, 祝安好

**Comment by kengwang** [comment]
稍微调查一下，预警时间是多久？在倒计时的过程中有没有出现什么问题？

**Comment by irasutoya** [comment]
我记得是50多秒，倒计时的语言有重叠呢，XX地区的那个和倒计时的声音有重叠
建议把定位做成自动的，可以调用系统的，ip定位也不错

**Comment by irasutoya** [comment]
可以把软件做成安装的那种，安装系统服务，这样地震来的时候可以有效的预警，弹窗的话可以放到右下角，预警的时候建议自动把系统声音调到最大，或者使用其他醒目的提示，加油！

**Comment by kengwang** [comment]
> 我记得是50多秒，倒计时的语言有重叠呢，XX地区的那个和倒计时的声音有重叠 建议把定位做成自动的，可以调用系统的，ip定位也不错

倒计时和地区重叠是刻意设计的, 因为我所在的位置只有 20 多秒, 在最短的时间传出最多的消息, 但是是否效果有些不好?
定位的话由于很多地方都是很多层 NAT, 我的 IP 定位和我的位置相差很远. 系统定位的话我当时没找到相关文档

**Comment by irasutoya** [comment]
嗯嗯

**Comment by kengwang** [comment]
> 预警的时候建议自动把系统声音调到最大，

这个可以有

**Comment by irasutoya** [comment]
https://lbs.amap.com/product/locate#/

**Comment by kengwang** [comment]
> https://lbs.amap.com/product/locate#/

我试了一下, 精度还行, 之后可能会采用

**Comment by irasutoya** [comment]
自动调节系统声音的可以放在设置里让用户自行选择

**Comment by irasutoya** [comment]
安装包有点大，有办法缩小安装包体积吗？

**Comment by kengwang** [comment]
可以先安装 .NET 6 运行时,然后再运行
但是为了方便, 因为 .NET 6 运行时下载要去微软那边,下载速度有点慢
所以就一起打包了

**Comment by irasutoya** [comment]
嗯，知道了

**Comment by irasutoya** [comment]
可以做成打开软件时直接就在地震列表页面
![image](https://user-images.githubusercontent.com/98635300/188542085-f240ce4f-0c8d-46f3-beb8-63c07ec0182e.png)

**Comment by irasutoya** [comment]
中国地震台网api也不错

**Comment by kengwang** [comment]
之前我看过中国地震台网,
仅论网页显示的内容的话, 是有个 5-10分钟的延迟的.

**Comment by kengwang** [comment]
现在打开是一个欢迎页面,(还未发布)

**Comment by irasutoya** [comment]
嗯，这样也不错

**Comment by irasutoya** [comment]
> 之前我看过中国地震台网, 仅论网页显示的内容的话, 是有个 5-10分钟的延迟的.

但是他们微博上就是实时发布，可以尝试联系他们获取实时api

**Comment by irasutoya** [comment]
> > 之前我看过中国地震台网, 仅论网页显示的内容的话, 是有个 5-10分钟的延迟的.
> 
> 但是他们微博上就是实时发布，可以尝试联系他们获取实时api

这样一款软件应该很受支持

**Comment by irasutoya** [comment]
可以给软件添加个图标吗？默认的图标有些不美观
