### ISSUE TITLE
有 API doc吗?

### ISSUE THREAD

**Issue by copyliu** [kengwang/EarthQuakeWarning#5]
接口地址是通过反编译来的吗? 其实我蛮好奇
https://github.com/kengwang/EarthQuakeWarning/blob/main/EarthquakeWaring.App/Services/HuaniaEarthQuakeApi.cs#L33
的 `3` 是什么奇妙的魔法参数

**Comment by kengwang** [comment]
抓的
3 代表的数据更新数
一般必须要 3 个台站提供的数据才有参考性
抓出来的参数就是这个

**Comment by XzaiCloud** [comment]
copyliu！

**Comment by intAV** [comment]
请问有websocket api吗，这种能达到秒级通知的系统内部应该不是使用的http协议吧，不然这个请求的多大呀，内部或许用的tcp长连接之类的吧ws://而且我觉得用http不太好，不太敢乱用

**Comment by kengwang** [comment]
按理说是的，但是暂时还没有弄到那种方式的相关接口。
目前只有这个抓出来的 API。
个人感觉确实有点滥用
________________________________
发件人: intAV ***@***.***>
发送时间: 2023年3月1日 6:01
收件人: kengwang/EarthQuakeWarning ***@***.***>
抄送: Kengwang ***@***.***>; State change ***@***.***>
主题: Re: [kengwang/EarthQuakeWarning] 有 API doc吗? (Issue #5)


请问有websocket api吗，这种能达到秒级通知的系统内部应该不是使用的http协议吧，不然这个请求的多大呀，内部或许用的tcp长连接之类的吧ws://而且我觉得用http不太好，不太敢乱用

―

**Comment by kengwang** [comment]
目前 Wolfx API 推出了 WebSocket 方式, 可能会在后期进行适配

**Comment by kengwang** [comment]
For API in WebSocket, please refer #17
