### ISSUE TITLE
预警时将系统声音调到最大

### ISSUE THREAD

**Issue by kengwang** [kengwang/EarthQuakeWarning#7]
> 预警的时候建议自动把系统声音调到最大，

_Originally posted by @kengwang in https://github.com/kengwang/EarthQuakeWarning/issues/3#issuecomment-1237613709_

**Comment by Initial-heart-1** [comment]
不理解为何这个 issue 被搁置如此长的时间？调整音量基于我的项目经验可以通过以下两种方式轻易实现：
- WinAPI
- 模拟多媒体键盘，其实还是在调 API

**Comment by kengwang** [comment]
> 不理解为何这个 issue 被搁置如此长的时间？调整音量基于我的项目经验可以通过以下两种方式轻易实现：
> 
> * WinAPI
> * 模拟多媒体键盘，其实还是在调 API



1. 因为此项目目前停留在了能用能跑的阶段, 并且我暂时没有花费时间和精力进行维护
2. 之前试过几个方法和 API, 但是都没有成功, 如果大佬可以提供帮助的话可以发一下相关 API 的名称供参考

Windows 编程新手, 不太熟悉相关 API
感谢

**Comment by Initial-heart-1** [comment]
> > 不理解为何这个 issue 被搁置如此长的时间？调整音量基于我的项目经验可以通过以下两种方式轻易实现：
> > 
> > * WinAPI
> > * 模拟多媒体键盘，其实还是在调 API
> 
> 1. 因为此项目目前停留在了能用能跑的阶段, 并且我暂时没有花费时间和精力进行维护
> 2. 之前试过几个方法和 API, 但是都没有成功, 如果大佬可以提供帮助的话可以发一下相关 API 的名称供参考
> 
> Windows 编程新手, 不太熟悉相关 API 感谢

方法一我也没有做过，理论可行，但模拟多媒体键盘我有证实可用且发布的源码。如果你需要，我可以发送给你供参考。

**Comment by Raspberry-Monster** [comment]
https://github.com/kengwang/EarthQuakeWarning/pull/9
已在本PR中实现

**Comment by Initial-heart-1** [comment]
> #9 已在本PR中实现

看起来是这样。能够提供相关的测试数据吗？

**Comment by Raspberry-Monster** [comment]
> > #9 已在本PR中实现
> 
> 看起来是这样。能够提供相关的测试数据吗？

可以自己拉取代码然后生成，把音量调至静音，然后利用模拟功能模拟地震。你会发现软件会叫的很大声
就像这样：哼哼哼 啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊（逃

**Comment by Initial-heart-1** [comment]
> > > #9 已在本PR中实现
> > 
> > 
> > 看起来是这样。能够提供相关的测试数据吗？
> 
> 可以自己拉取代码然后生成，把音量调至静音，然后利用模拟功能模拟地震。你会发现软件会叫的很大声 就像这样：哼哼哼 啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

太臭了，而且test/review跟我没关系，都merge了想必ow是测了（
而且本地没环境，不然早这么做了（

**Comment by Initial-heart-1** [comment]
所以 @kengwang 或许应该关闭这个 issue。

**Comment by kengwang** [comment]
Close #7


________________________________

**Comment by kengwang** [comment]
> Reply: https://github.com/kengwang/EarthQuakeWarning/issues/7#issuecomment-1357046971

Stupid GitHub.
