### ISSUE TITLE
[BUG] 开启启动表现异常

### ISSUE THREAD

**Issue by kengwang** [kengwang/EarthQuakeWarning#8]
似乎并不能正常开机启动, 排查排查哪里的问题

**Comment by irasutoya** [comment]
我这边打不开了，频繁闪退

**Comment by kengwang** [comment]
`Self-Dep` 版本还是 `No-Framework` 版本?

> 我这边打不开了，频繁闪退

**Comment by irasutoya** [comment]
> `Self-Dep` 版本还是 `No-Framework` 版本?
> 
> > 我这边打不开了，频繁闪退

[EarthquakeWaring.App-v1.0.3-win-x64-Self-Dep.exe](https://github.com/kengwang/EarthQuakeWarning/releases/download/1.0.3/EarthquakeWaring.App-v1.0.3-win-x64-Self-Dep.exe)

**Comment by kengwang** [comment]
经过测试, 此分发包出现严重问题! 感谢反馈. 此版本包出现严重问题 具体问题在 NotifyIcon 处, Icon 文件夹未创建时会出现问题. 将在下个版本修复

> > `Self-Dep` 版本还是 `No-Framework` 版本?
> > > 我这边打不开了，频繁闪退
> 
> [EarthquakeWaring.App-v1.0.3-win-x64-Self-Dep.exe](https://github.com/kengwang/EarthQuakeWarning/releases/download/1.0.3/EarthquakeWaring.App-v1.0.3-win-x64-Self-Dep.exe)

**Comment by irasutoya** [comment]
感谢

**Comment by kengwang** [comment]
经过测试, 由于开机启动时  Working Directory 错误, 所以无法正常启动

**Comment by irasutoya** [comment]
https://user-images.githubusercontent.com/98635300/189032665-8128cc51-99b1-421b-a143-d0f6f175f3e5.mp4

**Comment by kengwang** [comment]
> 2022-09-08.12-12-20.mp4

已知问题, 正在修复

**Comment by kengwang** [comment]
之后将不再分发单文件版, 因为不知道什么问题无法运行
